# Generated by Django 2.2 on 2021-03-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20210318_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='QuotesDoc',
        ),
        migrations.AddField(
            model_name='noticia',
            name='jornal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='noticia', to='noticias.Jornal'),
            preserve_default=False,
        ),
    ]
