# Generated by Django 2.2 on 2021-03-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20210318_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='jornal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='noticia', to='noticias.Jornal'),
        ),
    ]
