# Generated by Django 2.2 on 2021-03-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='media/')),
                ('data', models.DateField()),
                ('data_import', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
